### PR TITLE
fixing nil pointer erorr in the filter enrichment logic

### LINKED ISSUE #172: Nil pointer exception in event enrichment
> panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xbff489]
> goroutine 31 [running]:
> github.com/hyperledger/firefly-evmconnect/internal/ethereum.(*listener).filterEnrichEthLog(0xc0002cb710, {0x1398c60?, 0xc0001a20f0?}, 0x42?, {0x0?, 0x16?, 0x0?}, 0xf65b20?)
> 	/go/pkg/mod/github.com/hyperledger/firefly-evmconnect@v1.3.22-0.20250630202107-dca14e03401f/internal/ethereum/event_listener.go:258 +0x169
> github.com/hyperledger/firefly-evmconnect/internal/ethereum.(*eventStream).filterEnrichSort(0xc00074f5c0?, {0x1398c60, 0xc0001a20f0}, 0xc000258040, {0xc000696008, 0x1df, 0xf80640?})
> 	/go/pkg/mod/github.com/hyperledger/firefly-evmconnect@v1.3.22-0.20250630202107-dca14e03401f/internal/ethereum/event_stream.go:518 +0x41e
> github.com/hyperledger/firefly-evmconnect/internal/ethereum.(*eventStream).leadGroupSteadyState(0xc000235200)
> 	/go/pkg/mod/github.com/hyperledger/firefly-evmconnect@v1.3.22-0.20250630202107-dca14e03401f/internal/ethereum/event_stream.go:381 +0x715
> github.com/hyperledger/firefly-evmconnect/internal/ethereum.(*eventStream).streamLoop(0xc000235200)
> 	/go/pkg/mod/github.com/hyperledger/firefly-evmconnect@v1.3.22-0.20250630202107-dca14e03401f/internal/ethereum/event_stream.go:454 +0x65
> created by github.com/hyperledger/firefly-evmconnect/internal/ethereum.(*ethConnector).EventStreamStart in goroutine 1
> 	/go/pkg/mod/github.com/hyperledger/firefly-evmconnect@v1.3.22-0.20250630202107-dca14e03401f/internal/ethereum/event_actions.go:62 +0x3dc
>

### PR DESCRIPTION
**Pull request by Chengxuan**
resolves #172

### CODE REVIEW

File: internal/ethereum/event_enricher.go [hunk 1]
```diff
@@ -47,18 +47,24 @@ func (ee *eventEnricher) filterEnrichEthLog(ctx context.Context, f *eventFilter,
 	addrMatches := f.Address == nil || bytes.Equal(ethLog.Address[:], f.Address[:])
 	if !topicMatches || !addrMatches {
 		log.L(ctx).Debugf("skipping event '%s' topicMatches=%t addrMatches=%t", protoID, topicMatches, addrMatches)
-		return nil, matched, decoded, nil
```
Comment (matthew1001) [inline internal/ethereum/event_enricher.go:50]: Do `bool`s default initialise to `false` and this is just to tidy up the code, not change the logic?

File: internal/ethereum/event_enricher.go [hunk 2]
```diff
@@ -47,18 +47,24 @@ func (ee *eventEnricher) filterEnrichEthLog(ctx context.Context, f *eventFilter,
...
+		// by calling IsReady, ee.connector.chainID SHOULD be set to the chain ID when the connector is ready
 		resp, _, err := ee.connector.IsReady(ctx)
-		if !resp.Ready || err != nil {
+		if err != nil {
+			log.L(ctx).Errorf("Failed to set chain ID due to failed to query chain readiness: %+v", err)
 			return nil, matched, decoded, err
 		}
+		if !resp.Ready {
+			log.L(ctx).Errorf("Failed to set chain ID due to the connector is not ready")
+			return nil, matched, decoded, i18n.NewError(ctx, msgs.MsgFailedToRetrieveChainID)
```
Comment (matthew1001) [inline internal/ethereum/event_enricher.go:66]: Similarly here?

**Review by matthew1001 — APPROVED** [review]
LGTM with a couple of minor comments

File: internal/ethereum/event_enricher.go [hunk 3]
```diff
@@ -47,18 +47,24 @@ func (ee *eventEnricher) filterEnrichEthLog(ctx context.Context, f *eventFilter,
...
 
 	log.L(ctx).Infof("detected event '%s'", protoID)
 	data, decoded := ee.decodeLogData(ctx, f.Event, ethLog.Topics, ethLog.Data)
 
 	if len(ee.connector.chainID) == 0 {
+		// by calling IsReady, ee.connector.chainID SHOULD be set to the chain ID when the connector is ready
 		resp, _, err := ee.connector.IsReady(ctx)
-		if !resp.Ready || err != nil {
+		if err != nil {
+			log.L(ctx).Errorf("Failed to set chain ID due to failed to query chain readiness: %+v", err)
```
[the remark this answers is not in the document]
Comment (matthew1001) [reply internal/ethereum/event_enricher.go:61]: OK, that's fine

File: Dockerfile [hunk 4]
```diff
@@ -12,17 +12,15 @@ RUN make
...
 # Copy the migrations from FFTM down into our local migrations directory
 RUN DB_MIGRATIONS_DIR=$(go list -f '{{.Dir}}' github.com/hyperledger/firefly-transaction-manager/pkg/ffcapi | sed 's|pkg/ffcapi|db|') \
-    && cp -R $DB_MIGRATIONS_DIR db
+    && cp -R "$DB_MIGRATIONS_DIR" db
 
-
-FROM debian:buster-slim
+FROM alpine:3.21.3
 WORKDIR /evmconnect
+RUN addgroup -g 1001 evmgroup && adduser -D -u 1001 -G evmgroup evmuser
```
Comment (EnriqueL8) [inline Dockerfile:19]: This change broke the FF CLI volumes @dan-r , we need to revert this
